### ISSUE TITLE
source/includes/_customers.md ruby SDK guidance fails

### ISSUE THREAD

**Issue by gpolyn** [Dwolla/v2-ach-api-docs#34]
With dwolla_swagger 1.0.6 and ruby 2.1.2, the ruby SDK guidance at "Create a Customer funding source" fails with an unspecified `DwollaSwagger::ClientError` (at line 33 in .rb file linked below).

Recreate using [gist.github.com/gpolyn/53b8662c79aea9c9e335](https://gist.github.com/gpolyn/53b8662c79aea9c9e335), where `DWOLLA_UAT_ACCESS_TOKEN` is obtained from the token generator at [tokengenerator.dwolla.com](https://tokengenerator.dwolla.com/)

Would raise issue @ DwollaSwagger, but the api is not tested.

**Comment by spencerhunter** [comment]
Hi @gpolyn , We have it on our roadmap to make improvements to how the swagger ruby client handles errors. That being said, you are likely running into an error in this instance because you are either passing in an invalid routing number or using an expired access token. We'll look into adding a valid routing number to the docs that can be used for testing if the former may be the case..

I would highly recommend checking out a new v2 client we recently released which handles errors a little bit better. https://github.com/Dwolla/dwolla-v2-ruby
In addition, SDK and API support can be found on our support forum here: https://discuss.dwolla.com/c/api-support

**Comment by gpolyn** [comment]
OK, thanks for the comment.

Turns out the choice of `routingNumber` in uat may be key, and, therefore, something worthy of note in (future) docs?

Updated the gist to show what can be random and what can't: [gist.github.com/gpolyn/53b8662c79aea9c9e335](https://gist.github.com/gpolyn/53b8662c79aea9c9e335)

Finally, this ties-in with [developers.dwolla.com/guides/transfer-money-between-users/03-attach-unverified-bank.html](https://developers.dwolla.com/guides/transfer-money-between-users/03-attach-unverified-bank.html)
